spring:
  application:
    name: backend-user

  datasource:
    url: jdbc:postgresql://localhost:5432/backend_user
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  devtools:
    restart:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.tuempresa: DEBUG

jwt:
  secret: TecUnify_SecretKey_2025_MuySeguro_ParaProduccion_CambiarEsto_256bits_Minimo
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html